// @flow strict
export const DOCTORS_FETCH_REQUEST = '@@doctors/DOCTORS_FETCH_REQUEST';
export const DOCTORS_FETCH_SUCCESS = '@@doctors/DOCTORS_FETCH_SUCCESS';
export const DOCTORS_FETCH_FAILURE = '@@doctors/DOCTORS_FETCH_FAILURE';

export type DOCTORS_LIST_TYPE = Array<any>;

export type DOCTORS_FETCH_REQUEST_ACTION = {| type: typeof DOCTORS_FETCH_REQUEST |};
export type DOCTORS_FETCH_SUCCESS_ACTION = {| type: typeof DOCTORS_FETCH_SUCCESS, payload: DOCTORS_LIST_TYPE |};
export type DOCTORS_FETCH_FAILURE_ACTION = {| type: typeof DOCTORS_FETCH_FAILURE |};

export type Action =
  | DOCTORS_FETCH_REQUEST_ACTION
  | DOCTORS_FETCH_SUCCESS_ACTION
  | DOCTORS_FETCH_FAILURE_ACTION;
